name: Build
on:
  schedule:
    - cron:  '0 4 * * 1'
  push:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/dellelce/python-base

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Mkit Python
        run: docker build -t $IMAGE .
      - name: Python check version
        run: |
              PYTHON_VERSION=$(docker run --rm $IMAGE  /app/python/bin/python3 -V | awk ' NR == 1 { print $2; } ')
              echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
      - name: Add tag & push
        run: docker tag $IMAGE $IMAGE:$PYTHON_VERSION && docker push $IMAGE:$PYTHON_VERSION && docker push $IMAGE
